### ISSUE TITLE
Infinite synchronous streams

### ISSUE THREAD

**Issue by guckstift** [rpominov/basic-streams#21]
Hi there,

Currently the restriction exists that you can not stop a subscription of a stream delivering multiple synchronous events because the dispose-function has not yet been returned.

What if you would extend the protocol such that the callback/sink could signal the stream that it has enough (e.g. by returning with a special Symbol or a truthy value, similar to bacon js noMore value).

This way you could implement take/takeWhile more efficiently and you could even allow for infinite synchronous streams only limited with take* modifiers.

cheers

**Comment by rpominov** [comment]
Hi!

The Bacon's solution is also a bit limited, it doesn't allow to unsubscribe before the first event. Also, we can't unsubscribe indirectly for example:

```js
function someFunction() {
  if (someCondition) {
    unsubscribe()
  }
}

const unsubscribe = stream(x => {
  console.log(x)
  someFunction()
})
```

We would have to know that `someFunction` may cause unsubscription and will have to write it in code explicitly.

I find solution from proposal-observable with their `start` callback more flexible https://github.com/tc39/proposal-observable#observer . But adding another callback in basic-streams would ruin the simplicity.

We may still adopt the Bacon's solution but for now I'm not sure it is a good idea.

Also usually all this souldn't be a problem because streams should be asynchronous.
